#!/bin/sh
# postinst script for kse

set -e

case "$1" in
    configure)
        if [ -x /usr/bin/update-desktop-database ]; then
            update-desktop-database -q /usr/share/applications || true
        fi

        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
